version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cooling-postgres
    environment:
      POSTGRES_DB: coolingdb
      POSTGRES_USER: coolinguser
      POSTGRES_PASSWORD: coolingpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cooling-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cooling-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: coolinguser
      DB_PASS: coolingpass
      DB_NAME: coolingdb

volumes:
  postgres-data: