replicaCount: 1

image:
  repository: cooling-service
  pullPolicy: Never
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

ingress:
  enabled: true
  host: cooling.local